version: "3.8"

services:
  ui-tests:
    image: tp:v1
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: 2gb
    volumes:
      - ./report:/usr/src/app/report
      - ./:/usr/src/app
      - /dev/shm:/dev/shm
    working_dir: /usr/src/app
    command: >
      /bin/sh -c "\
        pytest -sv -o log_cli=true --alluredir=report -n=2 && \
        allure generate report -o report --clean"
    tty: true


  report:
    image: tp:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "ls -la && allure generate report --clean -o allure-report"
    working_dir: /usr/workspace