services:

  smoke-api-test:
    image: tp:v1
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: 2gb
    volumes:
      - ./:/usr/workspace
      - ./report:/usr/workspace/report
      - ./allure-report:/usr/workspace/allure-report  # <--- вот это
      - /dev/shm:/dev/shm
    working_dir: /usr/workspace
    command: >
      /bin/sh -c "mkdir -p report && pytest -sv -o log_cli=true --alluredir=report -n=2 && allure generate report -o allure-report --clean"
    tty: true