version: "3.8"

volumes:
  allure-data:

services:
  ui-tests:
    image: tp:v1
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: 2gb
    volumes:
      - ./:/usr/workspace
      - allure-data:/usr/workspace/allure-results
      - /dev/shm:/dev/shm
    working_dir: /usr/workspace
    command: >
      /bin/sh -c "\
        pytest -sv -o log_cli=true --alluredir=allure-results -n=2 || true"
    tty: true
    environment:
      LOGIN: ${LOGIN}
      PASSWORD: ${PASSWORD}
      MANAGER_LOGIN: ${MANAGER_LOGIN}
      MANAGER_PASSWORD: ${MANAGER_PASSWORD}

  report:
    image: tp:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
      - allure-data:/usr/workspace/allure-results
    working_dir: /usr/workspace
    command: >
      /bin/sh -c "ls -la allure-results && allure generate allure-results --clean -o allure-report"