version: "3.8"

services:
  ui-tests:
    image: tp:v1
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: 2gb
    volumes:
      - ./:/usr/workspace
      - /dev/shm:/dev/shm
    working_dir: /usr/src/app
    command: >
      /bin/sh -c "\
        pytest -sv -o log_cli=true --alluredir=report -n=2 || true"
    tty: true

  report:
    image: tp:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace

    command: /bin/sh -c "ls -la && allure generate allure-results --clean -o allure-report"
    working_dir: /usr/workspace